repos:
  - repo: local
    hooks:
      - id: make-lint
        name: make-lint
        language: system
        entry: make
        args: ['lint']
        pass_filenames: false
      - id: bashate
        name: bashate
        language: system
        entry: bashate
        args: ['--max-line-length', '120']
        types: [shell]
